### ISSUE TITLE
Command lines are not executed in the expected virtual environment

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/fsleyes-plugin-shimming-toolbox#21] opened 2022-02-18 18:55 UTC
### Environment details

- [x ] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/2_getting_started/1_installation.html)

Project version:

Current main branch

Python version: 3.7

### Bug Description
When we install the FSLeyes plugin (with make install), the following virtual environments are created:
- `base`           /Users/gaspard/shimming-toolbox/python
- `pst_venv`     /Users/gaspard/shimming-toolbox/python/envs/pst_venv (environment with the FSLeyes plugin)
- `st_venv`        /Users/gaspard/shimming-toolbox/python/envs/st_venv (environment with shimming-toolbox installed)

`st_venv` is the only one with shimming-toolbox installed and it should be used to run the functions called by the GUI.

When calling any function with the GUI, we use launchers as this one:

![image](https://user-images.githubusercontent.com/54723104/154750904-7370f8ab-92bf-4708-a1d2-c08ff0bfee2d.png)
Where the shebang specifies to use st_venv. However, the following error occurs in:

```bash
INFO: Running st_b1shim --algo 4 --b1map /Users/gaspard/git/data-testing/ds_tb1/sub-tb1tfl/fmap/sub-tb1tfl_TB1TFL_sagittal.nii.gz --output /Users/gaspard/git/fsleyes-plugin-shimming-toolbox/b1_shim_output
ERROR: [Errno 2] No such file or directory: ‘st_b1shim --algo 4 --b1map /Users/gaspard/git/data-testing/ds_tb1/sub-tb1tfl/fmap/sub-tb1tfl_TB1TFL_sagittal.nii.gz --output /Users/gaspard/git/fsleyes-plugin-shimming-toolbox/b1_shim_output’: ‘st_b1shim --algo 4 --b1map /Users/gaspard/git/data-testing/ds_tb1/sub-tb1tfl/fmap/sub-tb1tfl_TB1TFL_sagittal.nii.gz --output /Users/gaspard/git/fsleyes-plugin-shimming-toolbox/b1_shim_output’
```
Where the venv that is used seem to be pst_venv, which does not have shimming-toolbox installed.

Strangely, when the same command line is run from zsh, it works fine, no matter what environment is currently active (which is the expected behaviour of the launcher).

### Reproduction Steps
Follow the installation steps and try to run any shimming experiment.

### Potential Reasons behind Bug:
The subprocess.run() function seem to ignore the shebang specified in the launchers.
However, when replacing the launchers' shebang by the path to the `base` Python interpreter, it is not ignored anymore (but the functions still don't work, as shimming-toolbox is not installed in `base`)

### Additional Context:

@po09i let's add details here together.

**Comment by gaspardcereza** [comment] 2022-02-18 19:49
@kousu @joshuacwnewton If you have any insight on that matter, your help would be greatly appreciated cause we are completely stuck...

**Comment by joshuacwnewton** [comment] 2022-02-18 20:09
I'm currently wrapped up in the middle of something for SCT that I'm trying to finish up quickly before the weekend, but once I'm done that, I'd love to take a look at this. :) 

I have one quick question though, just to try to understand the context:

I noticed that there's a recently merged PR that touches the installer: https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/pull/19. Was the plugin script working OK with the old installation method? (i.e. Would you guess that this behaviour is the result of the changes in that PR?)

**Comment by gaspardcereza** [comment] 2022-02-18 20:26
@joshuacwnewton Indeed we changed the installation process recently with @po09i. We will try to check the GUI behavior previous to this change and keep you posted before you dig any further. Thanks for looking into that !

**Comment by po09i** [comment] 2022-02-18 21:15
@joshuacwnewton I reverted to the old version (before PR #19). I had to update to fsleyes 1.3.2 for an unrelated problem to get it working but it indeed did work before the PR.

What I think is going on: Before #19, we installed shimming toolbox in the same venv as fsleyes (pst_venv) which creates conflicts of versions but since it is inside pst_venv, the error Gaspard mentioned is not observed.

**Comment by gaspardcereza** [comment] 2022-02-18 23:41
I might have found a way to solve this by giving a environment variable to subprocess .run(): 

```python
HOME_DIR = str(Path.home())
PATH_ST_VENV = f"{HOME_DIR}/shimming-toolbox/python/envs/st_venv/bin"

def run_subprocess(cmd):
    """Wrapper for ``subprocess.run()`` that enables to input ``cmd`` as a full string
        (easier for debugging).

    Args:
        cmd (string): full command to be run on the command line
    """
    logging.info(f'{cmd}')
    try:
        subprocess.run(
            cmd.split(' '),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=True,
            env=dict(PATH=PATH_ST_VENV)
        )
```

@po09i let me think what you think of this option. I tried it and it works just fine with the B1+ shimming.

@jcohenadad that means that I should be able to make a demo video in time :)

**Comment by joshuacwnewton** [comment] 2022-02-21 15:13
Back from the weekend, sorry for the delay!

I think I've identified the root cause of the issue, and found a cleaner solution in https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/pull/22#discussion_r811217487. :)

**Closed as completed** 2022-02-22 22:57 UTC
Labels: bug
